application: qsorder-telegram-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: qsorder-bot.app

libraries:
 - name: beautifulsoup4
   version: "4.5.1"
 - name: pyTelegramBotAPI
   version: "2.1.5"

