application: qsorder-telegram-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: qsorder-bot.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: latest
